% This function is used to select top n components which conver 95% of all
% datasets from new features generated by PCA.
function [selected_features, latent] = pre_process_pca(raw_samples)
    
    % invoke the pca function from Matlab.
    [~, score, latent, ~, explained] = pca(raw_samples);
    energe_sum = 0;
    select_index = 0;
    
    while energe_sum <= 95
        select_index = select_index + 1;
        energe_sum = energe_sum + explained(select_index);
    end
    disp(select_index);
    % Return dataset of selected features from PCA
    selected_features = score(:, 1:select_index);
    
end